### ISSUE TITLE
`TypeError` thrown when computing changed files

### ISSUE THREAD

**Issue by stackptr** [freckle/commenter-action#120]
This action failed on a PR that does not touch the configuration:

<img width="951" alt="Screen Shot 2022-01-07 at 2 43 57 PM" src="https://user-images.githubusercontent.com/4542907/148616751-95dab0a0-455e-4c5a-9b83-978b070f9ccd.png">

```
Error: TypeError: Cannot read property 'slice' of undefined
Error: Cannot read property 'slice' of undefined
```

Other recent PRs using the same configuration do not have this error. There is only one instance of `slice` in this repo added in #106. Since the `file.patch.slice` comes after a map on `f: any`, this might be addressed by using the return type of `client.paginate` but a cursory search did not reveal what that would be.

**Comment by mjgpy3** [comment]
I bet `file.path` can be `undefined` in some cases (perhaps it omitted if the patch is too large?).
